"""Print the HTML content of a specific blog post for verification.
Usage: `python manage.py runscript print_blog_content` (if django-extensions) or
`python backend/print_blog_content.py` after setting DJANGO_SETTINGS_MODULE.
"""

import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "jdsite.settings")
django.setup()

from blog.models import BlogPost

slug = "2026-04-26_mejoras_ui_ux_blog_historico"
# Note: slug uses hyphens as generated by slugify from folder name
try:
    post = BlogPost.objects.get(slug=slug)
    print(post.content_html)
except BlogPost.DoesNotExist:
    print("BlogPost not found")
