# JAMEDIAZ.DEV
# JAMEDIAZ.DEV

# HTTP -> redirige siempre a HTTPS
server {
    listen 80;
    listen [::]:80;

    server_name jaimediaz.dev www.jaimediaz.dev;

    include snippets/security-headers.conf;
    # Agrandar buffers (evitar 403 en formularios grandes)
    client_body_buffer_size 1m;
    client_header_buffer_size 4k;
    large_client_header_buffers 4 8k;

    return 301 https://jaimediaz.dev$request_uri;
}

# HTTPS -> Django con Gunicorn (jdiaz_gunicorn.service)
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name jaimediaz.dev www.jaimediaz.dev;

    include snippets/security-headers.conf;
    # Agrandar buffers (evitar 403 en formularios grandes)
    client_body_buffer_size 1m;
    client_header_buffer_size 4k;
    large_client_header_buffers 4 8k;

    # Carpeta base del proyecto (no usamos index estático)
    root /var/www/jdiaz.tipsterbyte.com;

    # STATIC_ROOT (por el log se ve esto):
    # /var/www/jdiaz.tipsterbyte.com/app/backend/staticfiles/
    location /static/ {
        alias /var/www/jdiaz.tipsterbyte.com/app/backend/staticfiles/;
    }

    # MEDIA (ajusta si tu ruta real es otra)
    location /media/ {
        alias /var/www/jdiaz.tipsterbyte.com/app/backend/media/;
    }

    # TODAS las vistas dinámicas van a Django via Gunicorn
    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/jdiaz.tipsterbyte.com/app/run/jdiaz.sock;
        # ^^^ ESTE socket es exactamente el mismo que tienes en:
        # --bind unix:/var/www/jdiaz.tipsterbyte.com/app/run/jdiaz.sock
    }

    # Seguridad .ht
    location ~ /\.ht {
        deny all;
    }

    # Seguridad .git
    location ~ /\.git {
        deny all;
    }

    # SSL Let's Encrypt
    ssl_certificate     /etc/letsencrypt/live/jaimediaz.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/jaimediaz.dev/privkey.pem;   # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;                       # managed by Certbot
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;                 # managed by Certbot
}