# Generated by Django 5.2.8 on 2026-04-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_slug', models.CharField(db_index=True, max_length=200)),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('reaction_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reacción Blog',
                'verbose_name_plural': 'Reacciones Blog',
                'indexes': [models.Index(fields=['blog_slug', 'reaction_type'], name='reactions_b_blog_sl_d9c6c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('blog_slug', 'ip_address', 'reaction_type'), name='unique_reaction_per_ip_per_blog')],
            },
        ),
    ]
