# Generated by Django 5.2.8 on 2026-04-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.BigIntegerField(db_index=True)),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('reaction_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reacción Comentario Blog',
                'verbose_name_plural': 'Reacciones Comentarios Blog',
                'indexes': [models.Index(fields=['comment_id', 'reaction_type'], name='reactions_c_comment_6a7824_idx')],
                'constraints': [models.UniqueConstraint(fields=('comment_id', 'ip_address', 'reaction_type'), name='unique_reaction_per_ip_per_comment')],
            },
        ),
    ]
