# Generated by Django 5.2.8 on 2026-05-08 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_commentreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blogreaction',
            name='unique_reaction_per_ip_per_blog',
        ),
        migrations.RemoveConstraint(
            model_name='commentreaction',
            name='unique_reaction_per_ip_per_comment',
        ),
        migrations.AddField(
            model_name='blogreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='blogreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('blog_slug', 'user', 'reaction_type'), name='unique_reaction_per_user_per_blog'),
        ),
        migrations.AddConstraint(
            model_name='blogreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('blog_slug', 'ip_address', 'reaction_type'), name='unique_reaction_per_ip_per_blog'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('comment_id', 'user', 'reaction_type'), name='unique_reaction_per_user_per_comment'),
        ),
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('comment_id', 'ip_address', 'reaction_type'), name='unique_reaction_per_ip_per_comment'),
        ),
    ]
