# Generated by Django 5.2.8 on 2026-04-25 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_html', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('source_hash', models.CharField(help_text='Hash del archivo md para detectar cambios', max_length=64, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=120, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name': 'Entrada de blog',
                'verbose_name_plural': 'Entradas de blog',
                'ordering': ['-publish_date'],
            },
        ),
    ]
