# Generated by Django 5.2.8 on 2026-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='source_hash',
            field=models.CharField(db_index=True, help_text='Hash del archivo md para detectar cambios', max_length=64),
        ),
    ]
