# Generated by Django 5.2.8 on 2026-04-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_blogpost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_slug', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('content', models.TextField(max_length=1000)),
                ('ip_address', models.CharField(max_length=45)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blog_slug', 'status', 'created_at'], name='blog_blogco_blog_sl_393dd5_idx'), models.Index(fields=['parent'], name='blog_blogco_parent__06954d_idx'), models.Index(fields=['ip_address', 'created_at'], name='blog_blogco_ip_addr_729b6d_idx')],
            },
        ),
    ]
