# Generated by Django 5.2.8 on 2026-04-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.CharField(blank=True, help_text='Ruta a imagen de portada', max_length=500, null=True),
        ),
    ]
