# Generated by Django 5.2.8 on 2026-04-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='editable_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='identification_level',
            field=models.CharField(choices=[('anonymous', 'Anónimo'), ('identified', 'Identificado por email'), ('registered', 'Registrado (OAuth)')], default='anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('github', 'GitHub')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='provider_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
