# Generated by Django 5.2.8 on 2026-06-01 14:20
# HU-014: Anadir campo reading_time al modelo BlogPost

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blogcomment_id_alter_blogpost_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="reading_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Tiempo de lectura en minutos, leido del frontmatter "
                    "'tiempo_lectura' o 'reading_time'."
                ),
                null=True,
            ),
        ),
    ]
