# Generated by Django 5.2.8 on 2026-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Email del autor del artículo (del frontmatter)', max_length=150, null=True),
        ),
    ]
