# Generated by Django 5.2.8 on 2026-06-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogmoderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='approval_token',
            field=models.CharField(blank=True, help_text='Token único para aprobar el artículo vía URL', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='approval_token_created',
            field=models.DateTimeField(blank=True, help_text='Timestamp de creación del token de aprobación', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', help_text='Estado de moderación del artículo', max_length=20),
        ),
    ]
