# Generated by Django 5.2.8 on 2026-06-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost_approval_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Los artículos se crean como borradores. El administrador los publica desde la dashboard.'),
        ),
    ]
