# Generated by Django for HU-026-B

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0015_blogpost_created_at_blogpost_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                (
                    "value",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del admin",
                "verbose_name_plural": "Configuraciones del admin",
            },
        ),
    ]
