# Generated by Django 5.2.8 on 2026-06-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogemailconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogemailconfig',
            name='emails_enabled',
        ),
        migrations.AddField(
            model_name='blogemailconfig',
            name='admin_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Notificaciones al administrador: comentarios nuevos y borradores pendientes'),
        ),
        migrations.AddField(
            model_name='blogemailconfig',
            name='author_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Notificaciones al autor: artículo aprobado o rechazado'),
        ),
    ]
