# Generated by Django 5.2.8 on 2026-07-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_admin_config'),
        ('blog', '0019_remove_blogemailconfig_emails_enabled_and_more'),
    ]

    operations = [
    ]
