# Generated by Django 5.2.8 on 2026-07-08 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_merge_20260706_0318'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo del QR (ej: 'Calistenia - Cancha')", max_length=100)),
                ('slug', models.SlugField(help_text='Slug único para identificar el QR', max_length=100, unique=True)),
                ('slogan', models.CharField(blank=True, help_text='Eslogan o texto descriptivo de la campaña', max_length=200)),
                ('image_path', models.CharField(blank=True, help_text='Ruta relativa de la imagen QR guardada', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='QR activo actualmente')),
                ('blog_post', models.ForeignKey(blank=True, help_text='Artículo al que redirige el QR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='blog.blogpost')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el QR', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['-created_at'],
            },
        ),
    ]
