# Generated by Django 5.2.8 on 2025-11-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirythread",
            name="meeting_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquirythread",
            name="meeting_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inquirythread",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
