# Generated by Django 5.2.8 on 2025-12-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0002_inquirythread_meeting_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
